version: '3'
services:
  bof: 
   build: ./bof/
   volumes:
    - ./bof/share:/home/bof:ro
    - ./bof/xinetd:/etc/xineStd.d/bof:ro
    - ./tmp:/tmp:ro
   ports:
    - "10170:4597"
  shellcraft: 
   build: ./sc/
   volumes:
    - ./sc/share:/home/sc:ro
    - ./sc/xinetd:/etc/xinetd.d/sc:ro
    - ./tmp:/tmp:ro
   ports:
    - "10171:4597"